export default {
    autoComplete: 'value',
    suggestSearch: 'modelValue',
    siUpload: 'modelValue',
    siImageUpload: 'modelValue',
    siRichEditor2: 'modelValue',
    siUserPicker: 'modelValue',
    cascader: 'value',
    inputNumber: 'value',
    inputPassword: 'value',
    textarea: 'value',
    rate: 'value',
    slider: 'value',
    treeSelect: 'value',
    switch: 'checked',
}
